# Generated by Django 4.2.19 on 2025-03-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_admin_vuelos',
            field=models.BooleanField(default=False, help_text='Permite revertir vuelos a estado pendiente.'),
        ),
    ]
