# Generated by Django 4.2.19 on 2025-03-27 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_flight_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='aerolinea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='aeronaves', to='main.airline'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='parent_aircraft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='child_aircrafts', to='main.aircraft'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flight',
            name='aircraft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='flight_list', to='main.aircraft'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='flights', to='main.airline'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='billing_user',
            field=models.ForeignKey(blank=True, help_text='Usuario encargado de la facturación', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='billing_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flight',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_flights', to=settings.AUTH_USER_MODEL),
        ),
    ]
