# Generated by Django 4.2.19 on 2025-03-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_aircraft_aerolinea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archivado'),
        ),
    ]
