# Generated by Django 4.2.19 on 2025-03-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_aircraft_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
