# Generated by Django 4.2.19 on 2025-04-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_groupextension'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
