# Generated by Django 4.2.19 on 2025-04-02 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_documenttype_is_archived_alter_documenttype_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
