# Generated by Django 4.2.19 on 2025-04-02 20:19

from django.db import migrations, models
import main.models.archivable


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0011_alter_customuser_options_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', main.models.archivable.ActiveManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='documenttype',
            managers=[
                ('objects', main.models.archivable.ActiveManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='groupextension',
            name='is_archived',
        ),
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('permissions', models.ManyToManyField(blank=True, help_text='Permisos asignados a este grupo.', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', main.models.archivable.ActiveManager()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups_custom',
            field=models.ManyToManyField(blank=True, help_text='Grupos personalizados a los que pertenece este usuario.', related_name='users_custom', to='main.customgroup'),
        ),
    ]
