# Generated by Django 4.2.19 on 2025-04-02 21:27

from django.db import migrations, models
import main.models.archivable


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='aircraft',
            managers=[
                ('objects', main.models.archivable.ActiveManager()),
            ],
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
