# Generated by Django 4.2.19 on 2025-04-03 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_aircraft_managers_alter_aircraft_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupextension',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extension', serialize=False, to='main.customgroup'),
        ),
    ]
