# Generated by Django 4.2.19 on 2025-04-16 16:29

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models.archivable
import main.models.document


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_archived', models.BooleanField(default=False)),
                ('is_flight_supervisor', models.BooleanField(default=False, verbose_name='Supervisor de Vuelos')),
                ('is_billing_supervisor', models.BooleanField(default=False, verbose_name='Facturador de Vuelos')),
                ('is_admin_vuelos', models.BooleanField(default=False, help_text='Permite revertir vuelos a estado pendiente.')),
                ('groups', models.ManyToManyField(blank=True, help_text='(No usar) Campo requerido por Django internamente para permisos.', related_name='customuser_set', to='auth.group')),
            ],
            options={
                'default_permissions': (),
            },
            managers=[
                ('objects', main.models.archivable.ActiveManager()),
            ],
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(default=False)),
                ('aeronave', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'default_permissions': (),
            },
            managers=[
                ('objects', main.models.archivable.ActiveManager()),
            ],
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('permissions', models.ManyToManyField(blank=True, help_text='Permisos asignados a este grupo.', to='auth.permission')),
            ],
            options={
                'default_permissions': (),
            },
            managers=[
                ('objects', main.models.archivable.ActiveManager()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'default_permissions': (),
            },
            managers=[
                ('objects', main.models.archivable.ActiveManager()),
            ],
        ),
        migrations.CreateModel(
            name='NavigationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='GroupExtension',
            fields=[
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extension', serialize=False, to='main.customgroup')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='sections', to='auth.group')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('billed', 'Facturado')], default='pending', max_length=20)),
                ('aircraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='flight_list', to='main.aircraft')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='flights', to='main.airline')),
                ('billing_user', models.ForeignKey(blank=True, help_text='Usuario encargado de la facturación', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='billing_user', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_flights', to=settings.AUTH_USER_MODEL)),
                ('supervisors', models.ManyToManyField(blank=True, related_name='supervised_flights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('approve_flight', 'Puede aprobar vuelos'), ('mark_as_billed', 'Puede marcar vuelos como facturados'), ('admin_vuelos', 'Puede administrar vuelos (revertir estado)')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=main.models.document.generate_document_filename)),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.documenttype')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='main.flight')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('view_audit_detail', 'Puede ver los detalles de la auditoría')],
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='aircraft',
            name='aerolinea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='aeronaves', to='main.airline'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='parent_aircraft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='child_aircrafts', to='main.aircraft'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups_custom',
            field=models.ManyToManyField(blank=True, help_text='Grupos personalizados a los que pertenece este usuario.', related_name='users_custom', to='main.customgroup'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
