# Generated by Django 4.2.19 on 2025-03-21 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customuser_is_admin_vuelos'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_flights', to=settings.AUTH_USER_MODEL),
        ),
    ]
