# Generated by Django 4.2.19 on 2025-03-21 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_flight_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'permissions': [('approve_flight', 'Puede aprobar vuelos'), ('mark_as_billed', 'Puede marcar vuelos como facturados'), ('admin_vuelos', 'Puede administrar vuelos (revertir estado)')]},
        ),
    ]
