# Generated by Django 4.2.19 on 2025-02-16 01:01

from django.db import migrations, models
import main.models.document


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=main.models.document.generate_document_filename),
        ),
    ]
